import type { Paragraph } from 'docx';

/**
 * 계약서 다운로드 유틸리티
 * - PDF: html2canvas + jsPDF (한글 완벽 지원)
 * - Word: docx 라이브러리
 * - Text: 기본 Blob
 */

// PDF 다운로드 (한글 지원)
export async function downloadContractAsPDF(content: string, title: string): Promise<void> {
    try {
      // 동적 import
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ]);
  
      // 임시 컨테이너 생성 (화면에 보이지 않게)
      const container = document.createElement('div');
      container.style.cssText = `
        position: fixed;
        left: -9999px;
        top: 0;
        width: 210mm;
        padding: 20mm;
        background: white;
        font-family: 'Pretendard', 'Noto Sans KR', -apple-system, BlinkMacSystemFont, sans-serif;
        font-size: 12px;
        line-height: 1.8;
        color: #000;
      `;
  
      // 계약서 내용을 HTML로 변환
      const formattedContent = formatContractToHTML(content, title);
      container.innerHTML = formattedContent;
      document.body.appendChild(container);
  
      // 약간의 딜레이 (폰트 로딩 대기)
      await new Promise(resolve => setTimeout(resolve, 100));
  
      // HTML을 캔버스로 변환
      const canvas = await html2canvas(container, {
        scale: 2, // 고해상도
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });
  
      // 캔버스를 PDF로 변환
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = pdfWidth;
      const imgHeight = (canvas.height * pdfWidth) / canvas.width;
  
      let heightLeft = imgHeight;
      let position = 0;
  
      // 첫 페이지
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
  
      // 추가 페이지가 필요한 경우
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pdfHeight;
      }
  
      // 정리
      document.body.removeChild(container);
  
      // 다운로드
      pdf.save(`${sanitizeFilename(title)}.pdf`);
    } catch (error) {
      console.error('PDF 생성 오류:', error);
      throw new Error('PDF 다운로드에 실패했습니다. 텍스트 다운로드를 이용해주세요.');
    }
  }
  
  // 계약서 내용을 HTML로 포맷팅
  function formatContractToHTML(content: string, title: string): string {
    const lines = content.split('\n');
    let html = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="font-size: 22px; font-weight: bold; margin: 0;">${escapeHtml(title)}</h1>
        <div style="width: 100%; height: 2px; background: #333; margin-top: 15px;"></div>
      </div>
    `;
  
    for (const line of lines) {
      const trimmedLine = line.trim();
      
      if (!trimmedLine) {
        html += '<div style="height: 12px;"></div>';
        continue;
      }
  
      // 제X조 스타일
      if (/^제\d+조/.test(trimmedLine)) {
        html += `<div style="font-weight: bold; font-size: 14px; margin-top: 20px; margin-bottom: 10px;">${escapeHtml(trimmedLine)}</div>`;
      }
      // 숫자 리스트 (①②③ 또는 1. 2. 3.)
      else if (/^[①②③④⑤⑥⑦⑧⑨⑩]/.test(trimmedLine) || /^\d+\./.test(trimmedLine)) {
        html += `<div style="padding-left: 20px; margin-bottom: 6px;">${escapeHtml(trimmedLine)}</div>`;
      }
      // 일반 텍스트
      else {
        html += `<div style="margin-bottom: 6px;">${escapeHtml(trimmedLine)}</div>`;
      }
    }
  
    // 하단 정보
    html += `
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; text-align: center;">
        <p style="font-size: 10px; color: #666;">Generated by Lawdy AI</p>
        <p style="font-size: 10px; color: #666;">${new Date().toLocaleDateString('ko-KR')}</p>
      </div>
    `;
  
    return html;
  }
  
  // Word 다운로드 (docx)
  export async function downloadContractAsWord(content: string, title: string): Promise<void> {
    try {
      const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = await import('docx');
  
      const lines = content.split('\n');
      const children: Paragraph[] = [];
  
      // 제목
      children.push(
        new Paragraph({
          children: [new TextRun({ text: title, bold: true, size: 36 })],
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 12, color: '333333' },
          },
        })
      );
  
      // 내용
      for (const line of lines) {
        const trimmedLine = line.trim();
  
        if (!trimmedLine) {
          children.push(new Paragraph({ children: [], spacing: { after: 100 } }));
          continue;
        }
  
        // 제X조 스타일
        if (/^제\d+조/.test(trimmedLine)) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: trimmedLine, bold: true, size: 26 })],
              spacing: { before: 300, after: 150 },
            })
          );
        }
        // 숫자 리스트
        else if (/^[①②③④⑤⑥⑦⑧⑨⑩]/.test(trimmedLine) || /^\d+\./.test(trimmedLine)) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: trimmedLine, size: 22 })],
              indent: { left: 400 },
              spacing: { after: 80 },
            })
          );
        }
        // 일반 텍스트
        else {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: trimmedLine, size: 22 })],
              spacing: { after: 80 },
            })
          );
        }
      }
  
      // 하단 정보
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `Generated by Lawdy AI - ${new Date().toLocaleDateString('ko-KR')}`, size: 18, color: '666666' }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { before: 600 },
        })
      );
  
      const doc = new Document({
        sections: [{ children }],
      });
  
      const blob = await Packer.toBlob(doc);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${sanitizeFilename(title)}.docx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Word 생성 오류:', error);
      throw new Error('Word 다운로드에 실패했습니다.');
    }
  }
  
  // 텍스트 다운로드 (백업용)
  export function downloadContractAsText(content: string, title: string): void {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${sanitizeFilename(title)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
  
  // 파일명 정리
  function sanitizeFilename(name: string): string {
    return name.replace(/[<>:"/\\|?*]/g, '_').substring(0, 100);
  }
  
  // HTML 이스케이프
  function escapeHtml(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }